(package "trx-mode"
         "0.0.1"
         "Store project local variables.")

(website-url "https://github.com/mcraveiro/trx-mode")
(keywords "testing")

(package-file "trx-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "29")
(depends-on "cl-lib" "0.5")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
